[workspace]
members = [
    "crates/polars_structpath_types",
    "crates/polars_structpath_derive",
    "crates/polars_structpath",
    "crates/polars_protobuf",
    # "examples/example_protobuf"
]

resolver = "2"

[workspace.package]
version = "0.2.1"
edition = "2021"
license = "MIT"

[workspace.dependencies]
# Internal dependencies
polars-structpath-types = { version = "0.2.1", path = "crates/polars_structpath_types" }
polars-structpath-derive = { version = "0.2.1", path = "crates/polars_structpath_derive" }
polars-structpath = { version = "0.2.1", path = "crates/polars_structpath" }
polars-protobuf = { version = "0.2.1", path = "crates/polars_protobuf" }

# Common dependencies
bytes = "1.10.1"
paste = "1.0"
proc-macro2 = "1.0.103"
quote = "1.0.42"
thiserror = "1.0.69"
syn = { version = "2.0.111", features = ["full"] }

# Polars dependencies
polars-core = { version = "0.52.0", default-features = false }
polars-arrow = { version = "0.52.0", default-features = false }

# Protocol Buffers
prost = "0.14.1"
prost-build = "0.14.1"
prost-types = "0.14.1"

# Python bindings
pyo3 = { version = "0.26.0", features = ["abi3-py38"] }
pyo3-polars = { version = "0.25.0", features = ["derive"] }

# Serialization
serde = { version = "1.0.228", features = ["derive"] }

# Dev dependencies
trybuild = "1.0"

