[workspace]
members = [
    "structpath_types",
    "structpath_derive",
    "structpath",
    "structpath_protobuf",
    "structpath_protobuf_example"
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
# Internal dependencies
structpath_types = { version = "0.1.0", path = "structpath_types" }
structpath_derive = { version = "0.1.0", path = "structpath_derive" }
structpath = { version = "0.1.0", path = "structpath" }
structpath_protobuf = { version = "0.1.0", path = "structpath_protobuf" }

# Common dependencies
indexmap = "2.12.1"
proc-macro2 = "1.0.103"
quote = "1.0.42"
thiserror = "1.0.69"
syn = { version = "2.0.111", features = ["full"] }

# Polars dependencies
polars-core = { version = "0.52.0", default-features = false }
polars-arrow = { version = "0.52.0", default-features = false }

# Protocol Buffers
prost = "0.14.1"
prost-build = "0.14.1"
prost-types = "0.14.1"

# Python bindings
pyo3 = { version = "0.26.0", features = ["abi3-py38"] }
pyo3-polars = { version = "0.25.0", features = ["derive"] }

# Serialization
serde = { version = "1.0.228", features = ["derive"] }

# Dev dependencies
trybuild = "1.0"

