# Auto-generated Python bindings for protobuf messages
# DO NOT EDIT - generated by polars-protobuf build

from __future__ import annotations

from pathlib import Path

import polars as pl
from polars.plugins import register_plugin_function

_LIB = Path(__file__).resolve().parents[1]


class Address:
    """
    Polars expression plugins for Address protobuf message.

    Example:
        >>> import polars as pl
        >>> # Decode binary protobuf to struct
        >>> df.lazy().select(
        ...     Address.decode(pl.col("data")).alias("message")
        ... ).collect()
        >>>
        >>> # Encode struct to binary protobuf
        >>> df.lazy().select(
        ...     Address.encode(pl.col("message")).alias("data")
        ... ).collect()
    """

    @classmethod
    def encode(cls, expr: pl.Expr) -> pl.Expr:
        """
        Encode a struct column to binary protobuf.

        Args:
            expr: Expression selecting a struct column matching Address schema.

        Returns:
            Expression producing List[UInt8] with encoded protobuf bytes.
        """
        return register_plugin_function(
            plugin_path=_LIB,
            function_name="example_protobuf_Address_encode",
            args=[expr],
            is_elementwise=True,
        )

    @classmethod
    def decode(cls, expr: pl.Expr) -> pl.Expr:
        """
        Decode binary protobuf to a struct column.

        Args:
            expr: Expression selecting a List[UInt8] column with protobuf bytes.

        Returns:
            Expression producing struct column matching Address schema.
        """
        return register_plugin_function(
            plugin_path=_LIB,
            function_name="example_protobuf_Address_decode",
            args=[expr],
            is_elementwise=True,
        )


class Person:
    """
    Polars expression plugins for Person protobuf message.

    Example:
        >>> import polars as pl
        >>> # Decode binary protobuf to struct
        >>> df.lazy().select(
        ...     Person.decode(pl.col("data")).alias("message")
        ... ).collect()
        >>>
        >>> # Encode struct to binary protobuf
        >>> df.lazy().select(
        ...     Person.encode(pl.col("message")).alias("data")
        ... ).collect()
    """

    @classmethod
    def encode(cls, expr: pl.Expr) -> pl.Expr:
        """
        Encode a struct column to binary protobuf.

        Args:
            expr: Expression selecting a struct column matching Person schema.

        Returns:
            Expression producing List[UInt8] with encoded protobuf bytes.
        """
        return register_plugin_function(
            plugin_path=_LIB,
            function_name="example_protobuf_Person_encode",
            args=[expr],
            is_elementwise=True,
        )

    @classmethod
    def decode(cls, expr: pl.Expr) -> pl.Expr:
        """
        Decode binary protobuf to a struct column.

        Args:
            expr: Expression selecting a List[UInt8] column with protobuf bytes.

        Returns:
            Expression producing struct column matching Person schema.
        """
        return register_plugin_function(
            plugin_path=_LIB,
            function_name="example_protobuf_Person_decode",
            args=[expr],
            is_elementwise=True,
        )
