[project]
name = "polarspath"
version = "0.1.0"
description = "Polars Protobuf utilities"
authors = [{ name = "Javier Munarriz", email = "jmunarriz@gmx.com" }]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "polars",
    "protobuf==5.29.3",
    "pyarrow",
]

[dependency-groups]
dev = [
    "bandit",
    "maturin",
    "notebook",
    "pytest",
    "ruff>=0.12.7",
]

[tool.hatch.build.targets.sdist]
include = ["polarspath"]

[tool.hatch.build.targets.wheel]
include = ["polarspath"]

[tool.isort]
profile = "black"
line_length = 88

[build-system]
requires = ["maturin>=1.0,<2.0", "polars>=1.3.0"]
build-backend = "maturin"
