[package]
name = "polars_structpath"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "A library for dynamically accessing nested Rust structures using path notation"
repository = "https://github.com/jmunar/polarspath"
keywords = ["polars_structpath", "polars", "dataframe", "path", "access", "nested"]
categories = ["data-structures"]

[dependencies]
polars_structpath_derive = { workspace = true, optional = true }
polars_structpath_types = { workspace = true }
polars-core = { workspace = true, features = ["dtype-struct"] }

[dev-dependencies]
polars_structpath_derive = { workspace = true }
trybuild = { workspace = true }

[features]
default = ["std", "derive"]
derive = ["polars_structpath_derive"]
std = []
