[package]
name = "protobuf_sample"
version = "0.1.0"
edition = "2021"
description = "Sample Protocol Buffer messages for the polarspath project"
license = "MIT"

[dependencies]
prost = { version = "*" }
bytes = { version = "*" }
polars-core = { version = "*", features = ["dtype-array", "dtype-struct", "object"], default-features = false }
structpath = { path = "../structpath", features = ["derive"] }
structpath_types = { path = "../structpath_types" }
indexmap = "2.11.4"

[build-dependencies]
prost-build = { version = "*" }
