[package]
name = "protobuf_sample"
version = "0.1.0"
edition = "2021"
description = "Sample Protocol Buffer messages for the polarspath project"
license = "MIT"

[dependencies]
prost = { version = "*" }
structpath = { path = "../structpath", features = ["derive"] }
polars-core = { version = "*", features = ["dtype-array", "dtype-struct", "object"], default-features = false }

[build-dependencies]
prost-build = { version = "*" }
prost-types = { version = "*" }
