[package]
name = "protobuf_sample"
edition.workspace = true
description = "Sample Protocol Buffer messages for the polarspath project"
license = "MIT"

[lib]
name = "protobuf_sample"
crate-type = ["cdylib", "rlib"]

[features]
default = []
extension-module = ["pyo3", "pyo3/extension-module", "pyo3-polars", "serde"]

[dependencies]
prost = { workspace = true }
pyo3 = { workspace = true, optional = true }
pyo3-polars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
structpath = { workspace = true, features = ["derive"] }
structpath_protobuf = { workspace = true }

[build-dependencies]
structpath_protobuf = { workspace = true, features = ["build"] }
prost-build = { workspace = true }
prost-types = { workspace = true }
