//! Module for enum types with Polars categorical mapping support.
//!
//! This module provides the `EnumPath` trait for Rust enums that need to be
//! converted to Polars categorical types. It provides access to the categorical
//! mapping that maps enum variants to their Polars representation.

use crate::HasDataTypeWrapper;
use polars_core::prelude::{CategoricalMapping, DataType};
use std::sync::Arc;

/// Trait for types that represent enums with Polars categorical mapping support.
///
/// This trait enables conversion of Rust enums to Polars categorical values.
/// It provides access to the `CategoricalMapping` that maps enum variants to
/// their Polars representation.
///
/// # Purpose
///
/// When working with enums in Polars, they are represented as categorical types
/// with a mapping between variant names and their indices. This trait provides
/// access to that mapping, which is necessary for converting enum values to
/// Polars `AnyValue::Enum`.
///
/// # Implementation
///
/// This trait is typically implemented automatically by the `#[derive(EnumPath)]` macro
/// from the `polars_structpath_derive` crate. The implementation ensures that the
/// enum's data type is `DataType::Enum` and provides access to its categorical mapping.
///
/// # Example
///
/// ```ignore
/// use polars_core::prelude::AnyValue;
/// use polars_structpath_types::EnumPath;
///
/// // This would typically be generated by the EnumPath derive macro
/// #[derive(EnumPath)]
/// enum Status {
///     Active = 0,
///     Inactive = 1,
///     Pending = 2,
/// }
///
/// // After deriving EnumPath, you can access the mapping:
/// // let mapping = Status::mapping();
/// // This mapping can be used to convert enum values to Polars AnyValue::Enum
/// ```
pub trait EnumPath: HasDataTypeWrapper {
    /// Returns the Polars `CategoricalMapping` for this enum.
    ///
    /// The `CategoricalMapping` contains the mapping between enum variant names
    /// and their Polars categorical indices. This is used when converting enum
    /// values to `AnyValue::Enum`.
    ///
    /// # Returns
    ///
    /// A reference to the static `CategoricalMapping` for this enum type.
    ///
    /// # Panics
    ///
    /// This method will panic if the type's data type is not `DataType::Enum`.
    /// This should never happen if the trait is properly implemented by the derive macro.
    ///
    /// # Example
    ///
    /// ```rust,no_run
    /// use polars_structpath_types::EnumPath;
    ///
    /// // After deriving EnumPath on an enum:
    /// // let mapping = MyEnum::mapping();
    /// // The mapping can be used with AnyValue::Enum(index, mapping)
    /// ```
    fn mapping() -> &'static Arc<CategoricalMapping> {
        match Self::data_type() {
            DataType::Enum(_, ref mapping) => mapping,
            _ => unreachable!(),
        }
    }
}
