[package]
name = "structpath_protobuf_example"
edition.workspace = true
description = "Protocol Buffer messages with structpath support"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
extension-module = ["pyo3", "pyo3/extension-module", "pyo3-polars", "serde"]

[dependencies]
prost = { workspace = true }
structpath = { workspace = true, features = ["derive"] }
structpath_protobuf = { workspace = true }
pyo3 = { workspace = true, optional = true }
pyo3-polars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[build-dependencies]
structpath_protobuf = { workspace = true, features = ["build"] }
prost-build = { workspace = true }
prost-types = { workspace = true }
