# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: person.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'person.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\x12\x1bstructpath_protobuf_example\"\x91\x03\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x03\x12\x12\n\x05\x65mail\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x11\n\tis_active\x18\x04 \x01(\x08\x12<\n\x07\x61\x64\x64ress\x18\x05 \x01(\x0b\x32+.structpath_protobuf_example.Person.Address\x12\x0c\n\x04tags\x18\x06 \x03(\t\x12:\n\x06status\x18\x07 \x01(\x0e\x32*.structpath_protobuf_example.Person.Status\x12G\n\x12previous_addresses\x18\x08 \x03(\x0b\x32+.structpath_protobuf_example.Person.Address\x1a\x39\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x10\n\x08zip_code\x18\x03 \x01(\x05\"/\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08INACTIVE\x10\x02\x42\x08\n\x06_emailb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'person_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSON']._serialized_start=46
  _globals['_PERSON']._serialized_end=447
  _globals['_PERSON_ADDRESS']._serialized_start=331
  _globals['_PERSON_ADDRESS']._serialized_end=388
  _globals['_PERSON_STATUS']._serialized_start=390
  _globals['_PERSON_STATUS']._serialized_end=437
# @@protoc_insertion_point(module_scope)
