[package]
name = "structpath_types"
version = "0.1.0"
edition = "2021"
description = "Common objects for structpath and structpath_derive"
license = "MIT OR Apache-2.0"

[dependencies]
indexmap = "2.0"
polars-core = { version = "*", features = ["dtype-array", "dtype-struct", "dtype-categorical", "object"], default-features = false }
polars-dtype = { version = "*" }
proc-macro2 = "1.0"
quote = "1.0"
thiserror = "1.0"
