[package]
name = "structpath_types"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Common objects for structpath and structpath_derive"
repository = "https://github.com/jmunar/polarspath"
keywords = ["structpath", "polars", "dataframe", "path", "access"]
categories = ["data-structures", "no-std"]

[dependencies]
indexmap = { workspace = true }
polars-core = { workspace = true, features = ["dtype-struct", "dtype-categorical"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }
thiserror = { workspace = true }
