[package]
name = "structpath_types"
edition.workspace = true
description = "Common objects for structpath and structpath_derive"

[dependencies]
indexmap = { workspace = true }
polars-core = { workspace = true, features = ["dtype-struct", "dtype-categorical"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }
thiserror = { workspace = true }
