[package]
name = "structpath_derive"
edition.workspace = true
description = "Derive macros for structpath"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
structpath_types = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }
