[package]
name = "structpath_derive"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Derive macros for structpath"
repository = "https://github.com/jmunar/polarspath"
keywords = ["structpath", "derive", "macro", "proc-macro"]
categories = ["development-tools", "procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
structpath_types = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }
