[package]
name = "structpath"
edition.workspace = true
description = "A library for dynamically accessing nested Rust structures using path notation"

[dependencies]
structpath_derive = { workspace = true, optional = true }
structpath_types = { workspace = true }
polars-core = { workspace = true, features = ["dtype-struct"] }

[dev-dependencies]
structpath_derive = { workspace = true }
trybuild = { workspace = true }

[features]
default = ["std", "derive"]
derive = ["structpath_derive"]
std = []
