[package]
name = "polars_structpath_protobuf"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Automatic polars_structpath implementations for Protocol Buffer messages"
repository = "https://github.com/jmunar/polarspath"
keywords = ["polars_structpath", "protobuf", "protocol-buffers", "polars", "prost"]
categories = ["data-structures", "encoding"]

[features]
default = []
build = ["prost-build", "prost-types"]

[dependencies]
polars-arrow = { workspace = true }
polars-core = { workspace = true, features = ["dtype-array", "dtype-struct"] }
prost = { workspace = true }
polars_structpath = { workspace = true, features = ["derive"] }
prost-build = { workspace = true, optional = true }
prost-types = { workspace = true, optional = true }
