[package]
name = "polars_structpath_types"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Common objects for polars_structpath and polars_structpath_derive"
repository = "https://github.com/jmunar/polarspath"
keywords = ["polars_structpath", "polars", "dataframe", "path", "access"]
categories = ["data-structures", "no-std"]

[dependencies]
paste = { workspace = true }
polars-arrow = { workspace = true }
polars-core = { workspace = true, features = ["dtype-struct", "dtype-categorical"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }
thiserror = { workspace = true }
